# Generated by Django 4.1 on 2023-05-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_users_age_alter_users_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='icon',
            field=models.FileField(default='icon/unknown_usre.png', upload_to='icon/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='country'),
        ),
    ]
