# Generated by Django 4.1 on 2023-05-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_icon_alter_users_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='icon',
            field=models.FileField(default='icon/unknown_user.png', upload_to='icon/'),
        ),
    ]
