# Generated by Django 4.1 on 2023-05-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_users_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_tutor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
