# Generated by Django 4.1 on 2023-05-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_tutors', '0003_reviewoftutors_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewoftutors',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='book_tutors.booktutors'),
        ),
    ]
